#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.elf.C66{1,0,8.1,0
#
omp_config.xe66: package/cfg/omp_config.xe66.mak

clean::
	-$(RM) package/cfg/omp_config.xe66.mak
